import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: "Physical AI & Humanoid Robotics Textbook",
  tagline:
    "Master ROS 2, Digital Twin Simulation, NVIDIA Isaac, and Vision-Language-Action Robotics",
  favicon: "img/favicon.svg",

  // Set the production url of your site here
  url: "https://usmankhan0016.github.io",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/ai_native-textbook/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "usmankhan0016", // Usually your GitHub org/user name.
  projectName: "ai_native-textbook", // Usually your repo name.
  deploymentBranch: "gh-pages",
  trailingSlash: false,

  onBrokenLinks: "throw",

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  // Mermaid diagram support
  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },
  themes: ["@docusaurus/theme-mermaid"],

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
          // Remove this to remove the "edit this page" links.
          // editUrl: 'https://github.com/your-org/your-repo/tree/main/',

          // Enable custom frontmatter fields for RAG metadata
          beforeDefaultRemarkPlugins: [],
          beforeDefaultRehypePlugins: [],

          // Autogenerated sidebar from frontmatter
          sidebarCollapsible: true,
          sidebarCollapsed: false,

          // Watch for file changes in docs directory (enables HMR)
          editCurrentVersion: true,
          showLastUpdateAuthor: false,
          showLastUpdateTime: false,
        },
        blog: false, // Disable blog for textbook
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: "img/docusaurus-social-card.jpg",
    navbar: {
      title: "Physical AI Textbook",
      logo: {
        alt: "Physical AI Logo",
        src: "img/logo.svg",
      },
      items: [
        {
          type: "docSidebar",
          sidebarId: "tutorialSidebar",
          position: "left",
          label: "Textbook",
        },
        {
          href: "https://github.com/usmankhan0016/ai_native-textbook",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Modules",
          items: [
            {
              label: "Module 1: ROS 2",
              to: "/docs/module-1",
            },
          ],
        },
        {
          title: "Resources",
          items: [
            {
              label: "ROS 2 Documentation",
              href: "https://docs.ros.org/en/humble/",
            },
            {
              label: "NVIDIA Isaac Sim",
              href: "https://developer.nvidia.com/isaac-sim",
            },
          ],
        },
        {
          title: "More",
          items: [
            {
              label: "GitHub",
              href: "https://github.com/usmankhan0016/ai_native-textbook",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Physical AI & Humanoid Robotics Textbook. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ["python", "bash", "markup", "yaml"],
    },
    // Enable mermaid diagrams
    mermaid: {
      theme: { light: "neutral", dark: "dark" },
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
