import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars Configuration for Physical AI Textbook
 *
 * Key Design:
 * - tutorialSidebar uses autogeneration from docs/ but with explicit overrides for Module 4
 * - Module 4 categories have collapsed: false to ensure they stay open
 * - All categories have collapsible: true to allow users to toggle manually
 * - This prevents the "closing other modules when opening Module 4" bug
 */
const sidebars: SidebarsConfig = {
  // Main textbook sidebar with autogenerated content
  // Note: autogeneration respects overrides for categories with explicit collapsed/collapsible settings
  tutorialSidebar: [
    // Autogenerate from docs root, but with module-level controls
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

// Note: Individual module collapsibility is controlled via sidebar item metadata
// Module 4 items are configured to NOT collapse when other modules are opened
// See: docusaurus.config.ts sidebarCollapsible: true, sidebarCollapsed: false

export default sidebars;
